`timescale 1ns / 1ps

//------------------------------------------------------------------------------
// screen_mux.v
//
// Purpose:
//   Top-level screen multiplexer for the Optimus Prime VGA UI.
//
//   This module selects which screen is currently active, routes that screen's
//   font request to the shared font ROM, selects the active screen's pixel color,
//   and forwards navigation click pulses back to the UI FSM.
//
// Main responsibilities:
//   1) Instantiate all screen-rendering modules.
//   2) Route the active screen's font_char/font_row request to the shared ROM.
//   3) Select the active screen's pixel_color output.
//   4) Apply the animated barber-pole background effect to navy pixels.
//   5) Combine navigation pulses from the active screen path.
//   6) Forward sprite_enable during the Generating screen.
//
// Display mode encoding:
//   3'd0 = Menu
//   3'd1 = Params
//   3'd2 = Generating
//   3'd3 = Results
//   3'd4 = Error
//   3'd5 = Test Mode
//   3'd6 = Controls
//
// Font ROM sharing algorithm:
//   Only one screen is visible at a time. Each screen computes its own font ROM
//   request, but this mux forwards only the active screen's font_char/font_row to
//   the shared font ROM.
//
// Example:
//   If display_mode = MODE_RESULT, then result_font_char_w/result_font_row_w are
//   routed to the font ROM, and result_color_w is used as the raw pixel color.
//
// Background stripe algorithm:
//   Screen modules use COL_NAVY for the normal background. This mux replaces
//   some navy pixels with COL_STRIPE using two moving diagonal stripe patterns.
//   This creates the animated crosshatch/barber-pole background without requiring
//   each screen module to implement it separately.
//
// Notes:
//   - All logic runs in clk_vga.
//   - Mouse and UI status inputs must already be synchronized into clk_vga before
//     entering this module.
//   - Navigation outputs are one-clock pulses generated by the individual screen
//     modules.
//------------------------------------------------------------------------------

module screen_mux (
    input  wire        clk_vga,           // VGA pixel/render clock
    input  wire        resetn,            // Active-low reset synchronized to clk_vga

    //--------------------------------------------------------------------------
    // Active screen selector
    //--------------------------------------------------------------------------
    input  wire [2:0]  display_mode,      // Current screen selected by ui_fsm

    //--------------------------------------------------------------------------
    // Mouse state in clk_vga domain
    //--------------------------------------------------------------------------
    input  wire [9:0]  cursor_x,          // Current mouse cursor X coordinate
    input  wire [9:0]  cursor_y,          // Current mouse cursor Y coordinate
    input  wire        left_btn,          // Current left mouse button state

    //--------------------------------------------------------------------------
    // Current VGA pixel position
    //--------------------------------------------------------------------------
    input  wire [9:0]  pixel_x,           // Current pixel X coordinate
    input  wire [9:0]  pixel_y,           // Current pixel Y coordinate
    input  wire        pixel_active,      // High during visible display region

    //--------------------------------------------------------------------------
    // Screen data inputs from UI / compute system
    //--------------------------------------------------------------------------
    input  wire [1:0]  mode,              // Active compute mode
    input  wire [26:0] field0_val,        // Parameter-entry field 0 value
    input  wire [26:0] field1_val,        // Parameter-entry field 1 value
    input  wire        active_field,      // Active parameter field select
    input  wire        entry_done,        // Parameter entry done flag
    input  wire        input_error,       // Parameter input error flag
    input  wire        entry_active,      // High while editing a parameter field
    input  wire        cursor_blink,      // Blink signal for Params cursor

    input  wire [23:0] prime_count,       // Current/final prime count
    input  wire [26:0] current_n,         // Current candidate being tested
    input  wire [12:0] elapsed_sec,       // Elapsed time in seconds
    input  wire        compute_done,      // High when computation is complete
    input  wire [539:0] last_primes,      // Packed last-prime display values

    input  wire [26:0] largest_prime,     // Largest prime found
    input  wire        single_is_prime,   // Single-number primality result

    input  wire        test_running,      // Test Mode currently running
    input  wire        test_passed,       // Test Mode passed
    input  wire        test_failed,       // Test Mode failed
    input  wire        no_data_stored,    // Test Mode found no stored data
    input  wire [23:0] primes_checked,    // Number of primes compared in Test Mode
    input  wire [26:0] fail_ddr_val,      // First mismatched stored/DDR value
    input  wire [26:0] fail_sd_val,       // First mismatched SD reference value

    //--------------------------------------------------------------------------
    // Shared font ROM interface
    //--------------------------------------------------------------------------
    output reg  [6:0]  font_char,         // Character code sent to shared font ROM
    output reg  [3:0]  font_row,          // Font row sent to shared font ROM
    input  wire [7:0]  font_pixel_row,    // Pixel row returned by shared font ROM

    //--------------------------------------------------------------------------
    // Navigation outputs to ui_fsm
    //--------------------------------------------------------------------------
    output wire [1:0]  nav_mode_sel,      // Menu-selected compute mode
    output wire        nav_menu_click,    // Menu mode-button click pulse
    output wire        nav_back,          // Back-button click pulse
    output wire        nav_start,         // Params Start Finding click pulse
    output wire        nav_test_start,    // Test Mode Start Test click pulse
    output wire        nav_stop,          // Generating Stop click pulse
    output wire        nav_error_dismiss, // Error screen dismiss click pulse
    output wire        nav_controls,      // Menu Controls click pulse

    //--------------------------------------------------------------------------
    // Controls screen practice field
    //--------------------------------------------------------------------------
    input  wire [26:0] practice_val,      // Controls practice input value
    input  wire        practice_active,   // High while practice field is active
    input  wire        cursor_blink_ctrl, // Blink signal for Controls cursor

    //--------------------------------------------------------------------------
    // Sprite enable output
    //--------------------------------------------------------------------------
    output wire        sprite_enable,     // Enables sprite motion/display during Generating

    //--------------------------------------------------------------------------
    // Final pixel color output
    //--------------------------------------------------------------------------
    output reg  [3:0]  pixel_color        // Final palette nibble sent to frame writer
);

    //--------------------------------------------------------------------------
    // Display mode constants
    //--------------------------------------------------------------------------
    localparam MODE_MENU     = 3'd0; // Main menu screen
    localparam MODE_PARAMS   = 3'd1; // Parameter-entry screen
    localparam MODE_GEN      = 3'd2; // Generating/live-compute screen
    localparam MODE_RESULT   = 3'd3; // Results screen
    localparam MODE_ERROR    = 3'd4; // Error screen
    localparam MODE_TEST     = 3'd5; // Test Mode screen
    localparam MODE_CONTROLS = 3'd6; // Controls/help screen

    //--------------------------------------------------------------------------
    // Palette constants used by the background stripe overlay
    //--------------------------------------------------------------------------
    localparam COL_NAVY   = 4'h5; // Normal dark navy background color
    localparam COL_STRIPE = 4'h8; // Stripe overlay color

    //--------------------------------------------------------------------------
    // Barber-pole background coordinate pipeline
    //
    // The screen modules and font ROM path contain pipeline delay, so pixel_x
    // and pixel_y are delayed here before generating the stripe pattern.
    //--------------------------------------------------------------------------
    reg [9:0] bp_px_d1_ff, bp_px_d2_ff; // Delayed pixel X coordinates
    reg [9:0] bp_py_d1_ff, bp_py_d2_ff; // Delayed pixel Y coordinates

    //--------------------------------------------------------------------------
    // Barber-pole scroll state
    //
    // A new frame is detected when pixel_y returns to 0. The scroll value
    // advances every other frame to make the background move at half speed.
    //--------------------------------------------------------------------------
    reg [9:0] bp_prev_py_ff;       // Previous pixel_y value for frame detection
    reg       bp_frame_toggle_ff;  // Toggles each frame to divide scroll speed by two
    reg [8:0] bp_scroll_ff;        // Background stripe scroll offset

    always @(posedge clk_vga) begin
        // Reset stripe pipeline and scroll state.
        if (!resetn) begin
            bp_px_d1_ff        <= 10'd0;
            bp_px_d2_ff        <= 10'd0;
            bp_py_d1_ff        <= 10'd0;
            bp_py_d2_ff        <= 10'd0;
            bp_prev_py_ff      <= 10'd0;
            bp_frame_toggle_ff <= 1'b0;
            bp_scroll_ff       <= 9'd0;
        end
        else begin
            // Delay pixel coordinates to align the stripe overlay with output color.
            bp_px_d1_ff  <= pixel_x;
            bp_px_d2_ff  <= bp_px_d1_ff;
            bp_py_d1_ff  <= pixel_y;
            bp_py_d2_ff  <= bp_py_d1_ff;

            // Track previous Y coordinate to detect the start of a new frame.
            bp_prev_py_ff <= pixel_y;

            // At the start of each frame, toggle the divider and occasionally scroll.
            if ((pixel_y == 10'd0) && (bp_prev_py_ff != 10'd0)) begin
                bp_frame_toggle_ff <= ~bp_frame_toggle_ff;

                // Increment scroll every other frame.
                if (bp_frame_toggle_ff)
                    bp_scroll_ff <= bp_scroll_ff + 9'd1;
            end
        end
    end

    //--------------------------------------------------------------------------
    // Animated crosshatch stripe pattern
    //
    // Pattern A uses x + y - scroll.
    // Pattern B uses y - x - scroll.
    // If either pattern is active, navy pixels are replaced with stripe color.
    //--------------------------------------------------------------------------
    wire [9:0] bp_sum_a_w = bp_px_d2_ff + bp_py_d2_ff - {1'b0, bp_scroll_ff};
    wire [9:0] bp_sum_b_w = bp_py_d2_ff - bp_px_d2_ff - {1'b0, bp_scroll_ff};
    wire       bp_stripe_w = bp_sum_a_w[3] | bp_sum_b_w[3];

    //--------------------------------------------------------------------------
    // Per-screen font ROM request signals
    //--------------------------------------------------------------------------
    wire [6:0] menu_font_char_w;
    wire [3:0] menu_font_row_w;
    wire [6:0] params_font_char_w;
    wire [3:0] params_font_row_w;
    wire [6:0] gen_font_char_w;
    wire [3:0] gen_font_row_w;
    wire [6:0] result_font_char_w;
    wire [3:0] result_font_row_w;
    wire [6:0] error_font_char_w;
    wire [3:0] error_font_row_w;
    wire [6:0] test_font_char_w;
    wire [3:0] test_font_row_w;
    wire [6:0] ctrl_font_char_w;
    wire [3:0] ctrl_font_row_w;

    //--------------------------------------------------------------------------
    // Per-screen pixel color outputs
    //--------------------------------------------------------------------------
    wire [3:0] menu_color_w;
    wire [3:0] params_color_w;
    wire [3:0] gen_color_w;
    wire [3:0] result_color_w;
    wire [3:0] error_color_w;
    wire [3:0] test_color_w;
    wire [3:0] ctrl_color_w;

    //--------------------------------------------------------------------------
    // Navigation pulse outputs from individual screens
    //--------------------------------------------------------------------------
    wire [1:0] menu_sel_mode_w;        // Mode selected by Menu
    wire       menu_click_w;           // Menu mode click pulse
    wire [2:0] menu_hover_w;           // Menu hover index

    wire       menu_controls_click_w;  // Menu Controls click pulse

    wire       params_back_w;          // Params Back click pulse
    wire       params_start_w;         // Params Start click pulse
    wire       gen_stop_w;             // Generating Stop click pulse
    wire       gen_sprite_en_w;        // Generating screen sprite-enable signal
    wire       result_back_w;          // Results Back click pulse
    wire       error_dismiss_w;        // Error dismiss click pulse
    wire       test_start_w;           // Test Start click pulse
    wire       test_back_w;            // Test Back click pulse
    wire       ctrl_back_w;            // Controls Back click pulse

    //--------------------------------------------------------------------------
    // Screen: Menu
    //--------------------------------------------------------------------------
    screen_menu u_screen_menu (
        .clk_vga          (clk_vga),
        .resetn           (resetn),
        .cursor_x         (cursor_x),
        .cursor_y         (cursor_y),
        .left_btn         (left_btn),
        .pixel_x          (pixel_x),
        .pixel_y          (pixel_y),
        .pixel_active     (pixel_active),
        .font_char_ff     (menu_font_char_w),
        .font_row_ff      (menu_font_row_w),
        .font_pixel_row   (font_pixel_row),
        .selected_mode_ff (menu_sel_mode_w),
        .hover_index_w    (menu_hover_w),
        .click_pulse_ff   (menu_click_w),
        .controls_click_ff(menu_controls_click_w),
        .pixel_color_ff   (menu_color_w)
    );

    //--------------------------------------------------------------------------
    // Screen: Parameter entry
    //--------------------------------------------------------------------------
    screen_params u_screen_params (
        .clk_vga        (clk_vga),
        .resetn         (resetn),
        .mode           (mode),
        .field0_val     (field0_val),
        .field1_val     (field1_val),
        .active_field   (active_field),
        .entry_done     (entry_done),
        .input_error    (input_error),
        .entry_active   (entry_active),
        .cursor_blink   (cursor_blink),
        .cursor_x       (cursor_x),
        .cursor_y       (cursor_y),
        .left_btn       (left_btn),
        .pixel_x        (pixel_x),
        .pixel_y        (pixel_y),
        .pixel_active   (pixel_active),
        .font_char_ff   (params_font_char_w),
        .font_row_ff    (params_font_row_w),
        .font_pixel_row (font_pixel_row),
        .back_click_ff  (params_back_w),
        .start_click_ff (params_start_w),
        .pixel_color_ff (params_color_w)
    );

    //--------------------------------------------------------------------------
    // Screen: Generating
    //--------------------------------------------------------------------------
    screen_generating u_screen_generating (
        .clk_vga        (clk_vga),
        .resetn         (resetn),
        .mode           (mode),
        .prime_count    (prime_count),
        .current_n      (current_n),
        .elapsed_sec    (elapsed_sec),
        .compute_done   (compute_done),
        .last_primes    (last_primes),
        .cursor_x       (cursor_x),
        .cursor_y       (cursor_y),
        .left_btn       (left_btn),
        .pixel_x        (pixel_x),
        .pixel_y        (pixel_y),
        .pixel_active   (pixel_active),
        .font_char_ff   (gen_font_char_w),
        .font_row_ff    (gen_font_row_w),
        .font_pixel_row (font_pixel_row),
        .stop_click_ff  (gen_stop_w),
        .sprite_enable_w(gen_sprite_en_w),
        .pixel_color_ff (gen_color_w)
    );

    //--------------------------------------------------------------------------
    // Screen: Results
    //--------------------------------------------------------------------------
    screen_results u_screen_results (
        .clk_vga        (clk_vga),
        .resetn         (resetn),
        .mode           (mode),
        .single_is_prime(single_is_prime),
        .single_value   (field0_val),
        .prime_count    (prime_count),
        .elapsed_sec    (elapsed_sec),
        .largest_prime  (largest_prime),
        .last_primes    (last_primes),
        .cursor_x       (cursor_x),
        .cursor_y       (cursor_y),
        .left_btn       (left_btn),
        .pixel_x        (pixel_x),
        .pixel_y        (pixel_y),
        .pixel_active   (pixel_active),
        .font_char_ff   (result_font_char_w),
        .font_row_ff    (result_font_row_w),
        .font_pixel_row (font_pixel_row),
        .back_click_ff  (result_back_w),
        .pixel_color_ff (result_color_w)
    );

    //--------------------------------------------------------------------------
    // Screen: Error
    //--------------------------------------------------------------------------
    screen_error u_screen_error (
        .clk_vga         (clk_vga),
        .resetn          (resetn),
        .mode            (mode),
        .cursor_x        (cursor_x),
        .cursor_y        (cursor_y),
        .left_btn        (left_btn),
        .pixel_x         (pixel_x),
        .pixel_y         (pixel_y),
        .pixel_active    (pixel_active),
        .font_char_ff    (error_font_char_w),
        .font_row_ff     (error_font_row_w),
        .font_pixel_row  (font_pixel_row),
        .dismiss_click_ff(error_dismiss_w),
        .pixel_color_ff  (error_color_w)
    );

    //--------------------------------------------------------------------------
    // Screen: Test Mode
    //--------------------------------------------------------------------------
    screen_test u_screen_test (
        .clk_vga        (clk_vga),
        .resetn         (resetn),
        .test_running   (test_running),
        .test_passed    (test_passed),
        .test_failed    (test_failed),
        .no_data_stored (no_data_stored),
        .primes_checked (primes_checked),
        .fail_ddr_val   (fail_ddr_val),
        .fail_sd_val    (fail_sd_val),
        .cursor_x       (cursor_x),
        .cursor_y       (cursor_y),
        .left_btn       (left_btn),
        .pixel_x        (pixel_x),
        .pixel_y        (pixel_y),
        .pixel_active   (pixel_active),
        .font_char_ff   (test_font_char_w),
        .font_row_ff    (test_font_row_w),
        .font_pixel_row (font_pixel_row),
        .start_click_ff (test_start_w),
        .back_click_ff  (test_back_w),
        .pixel_color_ff (test_color_w)
    );

    //--------------------------------------------------------------------------
    // Screen: Controls
    //--------------------------------------------------------------------------
    screen_controls u_screen_controls (
        .clk_vga        (clk_vga),
        .resetn         (resetn),
        .cursor_x       (cursor_x),
        .cursor_y       (cursor_y),
        .left_btn       (left_btn),
        .pixel_x        (pixel_x),
        .pixel_y        (pixel_y),
        .pixel_active   (pixel_active),
        .font_char_ff   (ctrl_font_char_w),
        .font_row_ff    (ctrl_font_row_w),
        .font_pixel_row (font_pixel_row),
        .practice_val   (practice_val),
        .practice_active(practice_active),
        .cursor_blink   (cursor_blink_ctrl),
        .back_click_ff  (ctrl_back_w),
        .pixel_color_ff (ctrl_color_w)
    );

    //--------------------------------------------------------------------------
    // Font ROM request mux
    //
    // Routes the active screen's font request to the shared font ROM.
    //--------------------------------------------------------------------------
    always @(*) begin
        case (display_mode)
            MODE_MENU: begin
                font_char = menu_font_char_w;
                font_row  = menu_font_row_w;
            end

            MODE_PARAMS: begin
                font_char = params_font_char_w;
                font_row  = params_font_row_w;
            end

            MODE_GEN: begin
                font_char = gen_font_char_w;
                font_row  = gen_font_row_w;
            end

            MODE_RESULT: begin
                font_char = result_font_char_w;
                font_row  = result_font_row_w;
            end

            MODE_ERROR: begin
                font_char = error_font_char_w;
                font_row  = error_font_row_w;
            end

            MODE_TEST: begin
                font_char = test_font_char_w;
                font_row  = test_font_row_w;
            end

            MODE_CONTROLS: begin
                font_char = ctrl_font_char_w;
                font_row  = ctrl_font_row_w;
            end

            default: begin
                font_char = 7'h20;
                font_row  = 4'd0;
            end
        endcase
    end

    //--------------------------------------------------------------------------
    // Raw pixel color mux
    //
    // Selects the active screen's palette color before the animated background
    // overlay is applied.
    //--------------------------------------------------------------------------
    reg [3:0] raw_color; // Active screen color before background stripe overlay

    always @(*) begin
        case (display_mode)
            MODE_MENU:     raw_color = menu_color_w;
            MODE_PARAMS:   raw_color = params_color_w;
            MODE_GEN:      raw_color = gen_color_w;
            MODE_RESULT:   raw_color = result_color_w;
            MODE_ERROR:    raw_color = error_color_w;
            MODE_TEST:     raw_color = test_color_w;
            MODE_CONTROLS: raw_color = ctrl_color_w;
            default:       raw_color = COL_NAVY;
        endcase
    end

    //--------------------------------------------------------------------------
    // Final pixel color register
    //
    // Applies the animated stripe overlay only to navy background pixels. All
    // text, buttons, and other non-navy screen pixels pass through unchanged.
    //--------------------------------------------------------------------------
    always @(posedge clk_vga) begin
        // Reset output to the normal background color.
        if (!resetn) begin
            pixel_color <= COL_NAVY;
        end
        else begin
            // Replace selected navy background pixels with the stripe color.
            if (raw_color == COL_NAVY && bp_stripe_w)
                pixel_color <= COL_STRIPE;
            // Non-background pixels keep the active screen's original color.
            else
                pixel_color <= raw_color;
        end
    end

    //--------------------------------------------------------------------------
    // Navigation output assignments
    //
    // Navigation pulses are produced inside each screen module. These assignments
    // forward the pulses that the parent ui_fsm needs to change screens.
    //--------------------------------------------------------------------------
    assign nav_mode_sel      = menu_sel_mode_w;
    assign nav_menu_click    = menu_click_w;
    assign nav_back          = params_back_w | result_back_w | test_back_w | ctrl_back_w;
    assign nav_controls      = menu_controls_click_w;
    assign nav_start         = params_start_w;
    assign nav_test_start    = test_start_w;
    assign nav_stop          = gen_stop_w;
    assign nav_error_dismiss = error_dismiss_w;

    //--------------------------------------------------------------------------
    // Sprite enable
    //
    // Sprites are enabled only on the Generating screen when that screen requests
    // them.
    //--------------------------------------------------------------------------
    assign sprite_enable = (display_mode == MODE_GEN) && gen_sprite_en_w;

endmodule